name: Tea Is Fantastic
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  OUTPUT_PATH: '${{ github.workspace }}/output'
  DATA_PATH: '${{ github.workspace }}/data'
  APP_PATH: '${{ github.workspace }}/app'
  ANDROID_PATH: '${{ github.workspace }}/output/android'
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: halaat
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Python stuff
        run: |
          mkdir output
          pip install -r app/requirements.txt
          python app/scripts/main.py

      - name: Build bundle
        working-directory: ${{ env.OUTPUT_PATH }}
        run: | 
          npx react-native bundle --dev false --platform android --entry-file index.js --bundle-output ${{ env.ANDROID_PATH }}/app/src/main/assets/index.android.bundle --assets-dest ${{ env.ANDROID_PATH }}/app/src/main/res

      - name: Build apk
        working-directory: ${{ env.ANDROID_PATH }}
        run: | 
          ./gradlew assembleDebug
          cp ${{ env.ANDROID_PATH }}/app/build/outputs/apk/app-debug.apk ${{ env.OUTPUT_PATH }}

      - name: Push changes
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'output'
          destination-github-username: 'asfandyarsheikh'
          destination-repository-name: 'asfandyar-expo'
          user-email: github-actions[bot]@users.noreply.github.
          user-name: github-actions[bot]
          target-branch: main