name: Tea Is Fantastic
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  OUTPUT_PATH: '${{ github.workspace }}/output'
  DATA_PATH: '${{ github.workspace }}/data'
  APP_PATH: '${{ github.workspace }}/app'
  ANDROID_PATH: '${{ github.workspace }}/output/android'
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: halaat
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Python stuff
        - run: mkdir output
        - run: pip install -r app/requirements.txt
        - run: python app/scripts/main.py

      - name: Build apk
        - run: 'cd ${{ env.OUTPUT_PATH }} && npx react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res'
        - run: 'cd ${{ env.ANDROID_PATH }} && ./gradlew assembleDebug'
        - run: 'cp ${{ env.ANDROID_PATH }}/app/build/outputs/apk/app-debug.apk ${{ env.OUTPUT_PATH }}'

      - name: Push changes
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'output'
          destination-github-username: 'asfandyarsheikh'
          destination-repository-name: 'asfandyar-expo'
          user-email: github-actions[bot]@users.noreply.github.
          user-name: github-actions[bot]
          target-branch: main
        build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
        # uses: stefanzweifel/git-auto-commit-action@v4
        # with:
        #   repository: output
        #   branch: output
        #   push_options: '--force'
        #   skip_checkout: true


